version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  test:
    docker:
      - image: circleci/openjdk:9-jdk
    steps:
      - checkout
      - run:
          name: Test and coverage report
          command: ./gradlew check codeCoverageReport -PsystemTests -DchallongeUsername=${CHALLONGE_USERNAME} -DchallongeApiKey=${CHALLONGE_API_KEY} -DchallongeTournamentUrl=${CHALLONGE_TOURNAMENT_URL}
      - codecov/upload:
          file: build/reports/jacoco/report.xml
workflows:
  version: 2.1
  build:
    jobs:
    - test